lib/brickcroft_web/router.ex
defmodule BrickcroftWeb.Router do
  use BrickcroftWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :frontend do


  end

  pipeline :admin do
    plug BrickcroftWeb.Plugs.AdminLayout
    plug BrickcroftWeb.Plugs.LoadUser

  end

  scope "/", BrickcroftWeb do
    pipe_through [:browser, BrickcroftWeb.Plugs.LoadUser]

    get "/", PageController, :index

    get "/admin", Admin.SessionController, :new
    post "/admin", Admin.SessionController, :create

    get "/home", PageController, :dashboard

    get "/forgotpassword", Admin.SessionController, :recover_password
    get "/:slug", PageController, :show_by_slug
    post "/forgotpassword", Admin.SessionController, :recover_password_submit
    post "/enquiry", PageController, :contact

    get "/resetpassword/:code", Admin.SessionController, :reset_password
    post "/resetpassword/:code", Admin.SessionController, :reset_password_submit



  end

  scope "/admin", BrickcroftWeb.Admin, as: :admin  do
    pipe_through [:browser, :admin, BrickcroftWeb.Plugs.AuthenticateUser]
    get "/logout", SessionController, :delete
    get "/changepassword", SessionController, :change_password
    post "/changepassword", SessionController, :change_password_submit

    get "/userprofile", UserController, :userprofile
    post "/userprofile", UserController, :userprofile_submit


    resources "/settings", SettingController , only: [:edit, :update, :new,:create]
    resources "/images", ImageGalleryController

    resources "/users", UserController
    resources "/webpages", WebpageController
    resources "/features", FeatureController
    resources "/featuresimage", FeatureImageController
    resources "/services", MedicalServiceController
    resources "/categories", CategoryController
    resources "/sub_categories", SubCategoryController
    resources "/contacts", ContactController
    resources "/addresses", ContactAddressController
    resources "/teams", TeamController


  end

  # Other scopes may use custom stacks.
  # scope "/api", BrickcroftWeb do
  #   pipe_through :api
  # end
end

lib/brickcroft_web/views/layout_view.ex
defmodule BrickcroftWeb.LayoutView do
  use BrickcroftWeb, :view
end

lib/brickcroft_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>BrickCroft Construction | Admin Dashboard</title>

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="<%= Routes.static_path(@conn,"/css/plugins/toastr/toastr.min.css") %>" rel="stylesheet">



    <link href="<%= Routes.static_path(@conn,"/css/animate.css") %>" rel="stylesheet">
    <link href="<%= Routes.static_path(@conn, "/css/style.css") %>" rel="stylesheet">

</head>

<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element"> <span>

                             </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><%= "#{@conn.assigns.current_user.firstname}  #{@conn.assigns.current_user.lastname}" %></strong>
                             </span> <span class="text-muted text-xs block">Staff <b class="caret"></b></span> </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="<%= Routes.admin_user_path(@conn, :userprofile) %>">Profile</a></li>
                                <li><a href="<%= Routes.admin_session_path(@conn,:change_password)%>">Change Password</a></li>

                                <li class="divider"></li>
                                <li><a href="<%= Routes.admin_session_path(@conn,:delete) %>">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            BCL Admin
                        </div>
                    </li>


 <li>
                        <a target="_blank" href="<%= Routes.page_path(@conn, :index) %>"><i class="fa fa-home   "></i> <span class="nav-label">Main Website</span></a>
                    </li>

                    <li>
                        <a href="<%= Routes.session_path(@conn, :new) %>"><i class="fa fa-diamond"></i> <span class="nav-label">Dashboard</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-group"></i> <span class="nav-label">Users</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="<%= Routes.admin_user_path(@conn, :index) %>">List User</a></li>
                            <li><a href="<%= Routes.admin_user_path(@conn, :new) %>">Add user</a></li>

                        </ul>
                    </li>

                       <li>
                                            <a href="#"><i class="fa fa-file-o"></i> <span class="nav-label">Pages</span><span class="fa arrow"></span></a>
                                            <ul class="nav nav-second-level collapse">
                                                <li><a href="<%= Routes.admin_webpage_path(@conn, :index) %>"> List Pages </a></li>
                                                <li><a href="<%= Routes.admin_webpage_path(@conn, :new) %>">Add Page </a></li>

                                            </ul>
                                        </li>

  <li>
                                            <a href="#"><i class="fa fa-location-arrow"></i> <span class="nav-label">Contact Info</span><span class="fa arrow"></span></a>
                                            <ul class="nav nav-second-level collapse">
                                                <li><a href="<%= Routes.admin_contact_path(@conn, :index) %>"> List Contact </a></li>
                                                <li><a href="<%= Routes.admin_contact_path(@conn, :new) %>">Add Contact </a></li>

                                            </ul>
                                        </li>



                    <li>
                        <a href="#"><i class="fa fa-files-o"></i> <span class="nav-label">Images Gallery</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="<%= Routes.admin_image_gallery_path(@conn,:index) %>">List Gallery</a></li>
                            <li><a href="<%= Routes.admin_image_gallery_path(@conn,:new) %>">Add Image</a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-globe"></i> <span class="nav-label">Features</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="<%= Routes.admin_feature_path(@conn,:index)%>">List Features</a></li>
                            <li><a href="<%= Routes.admin_feature_path(@conn,:new)%>">Add Feature</a></li>
                            <li><a href="<%= Routes.admin_feature_image_path(@conn,:index)%>">List Features Pictures </a></li>


                        </ul></li>


                              <li>
                                                <a href="#"><i class="fa fa-globe"></i> <span class="nav-label">Company Services</span><span class="fa arrow"></span></a>
                                                <ul class="nav nav-second-level collapse">
                                                    <li><a href="<%= Routes.admin_medical_service_path(@conn,:index)%>">List Services</a></li>
                                                    <li><a href="<%= Routes.admin_medical_service_path(@conn,:new)%>">Add Service</a></li>


                                                </ul></li>


                               <li>
                                                                             <a href="#"><i class="fa fa-globe"></i> <span class="nav-label"> Team </span><span class="fa arrow"></span></a>
                                                                             <ul class="nav nav-second-level collapse">
                                                                                 <li><a href="<%= Routes.admin_team_path(@conn,:index)%>">List Team</a></li>
                                                                                 <li><a href="<%= Routes.admin_team_path(@conn,:new)%>">Add Team</a></li>


                                                                             </ul></li>



                         <li>
                                                <a href="<%= Routes.admin_setting_path(@conn,:new)%>"><i class="fa fa-globe"></i> <span class="nav-label">General Settings</span></a></li>







                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">

            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome <%= @conn.assigns.current_user.firstname %></span>
                </li>



                <li>
                    <a href="<%= Routes.admin_session_path(@conn,:delete) %>">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
                <li>
                    <a class="right-sidebar-toggle">
                        <i class="fa fa-tasks"></i>
                    </a>
                </li>
            </ul>

        </nav>
        </div>
  <%= render @view_module, @view_template, assigns %>


        </div>


    </div>

   <script src="<%= Routes.static_path(@conn,"/js/app.js") %>"></script>


<script src="<%= Routes.static_path(@conn,"/js/plugins/toastr/toastr.min.js") %>"></script>

    <!-- Mainly scripts -->
    <script src="<%= Routes.static_path(@conn, "/js/plugins/metisMenu/jquery.metisMenu.js") %>"></script>
    <script src="<%= Routes.static_path(@conn, "/js/plugins/slimscroll/jquery.slimscroll.min.js") %>"></script>




    <!-- Custom and plugin javascript -->
    <script src="<%= Routes.static_path(@conn, "/js/inspinia.js") %>"></script>
    <script src="<%= Routes.static_path(@conn, "/js/plugins/pace/pace.min.js") %>"></script>

    <!-- jQuery UI -->
    <script src="<%= Routes.static_path(@conn, "/js/plugins/jquery-ui/jquery-ui.min.js") %>"></script>

<script src="https://cdn.ckeditor.com/ckeditor5/11.2.0/classic/ckeditor.js"></script>



<script>
var editor;
ClassicEditor.create( document.querySelector( '.editor' ),{

 toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote' ],
        heading: {
            options: [
                { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
                { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
                { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' }
            ]}})

				.catch( error => {
					console.error( error );
				} );

if(document.querySelector(".editor")){
document.querySelector(".editor").required = false;
}


</script>


<%= if get_flash(@conn, :info) do %>

<script type="text/javascript">
 console.info("Infor here");
        $(document).ready(function() {

            setTimeout(function() {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 4000
                };
                toastr.info("<%= get_flash(@conn, :info) %>");

            }, 1300);
            });
    </script>
<% end %>



<%= if get_flash(@conn, :error) do %>
<script>


        $(document).ready(function() {

            setTimeout(function() {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 4000
                };
                toastr.error("<%= get_flash(@conn, :error) %>");

            }, 1300);
            });
    </script>
<% end %>


</body>
</html>
<link rel="stylesheet" type="text/css" href="<%= Routes.static_path(@conn,"/css/simditor.css") %>" />


<script type="text/javascript" src="<%= Routes.static_path(@conn,"/js/module.js") %>"></script>
<script type="text/javascript" src="<%= Routes.static_path(@conn,"/js/hotkeys.js") %>"></script>

<script type="text/javascript" src="<%= Routes.static_path(@conn,"/js/simditor.js") %>"></script>

<script>

var smd = new Simditor({
  textarea: $('#editor')
  //optional options
});
</script>

lib/brickcroft_web/templates/layout/admin_login.html.eex
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>BCL Admin | Login</title>

    <link href="<%= Routes.static_path(@conn, "/css/app.css") %>" rel="stylesheet">
<link href="<%= Routes.static_path(@conn,"/css/plugins/toastr/toastr.min.css") %>" rel="stylesheet">
    <link href="<%= Routes.static_path(@conn ,"/css/style.css") %>" rel="stylesheet">

</head>


<body class="gray-bg">






          <%= render @view_module, @view_template, assigns %>

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>

<script src="<%= Routes.static_path(@conn,"/js/plugins/toastr/toastr.min.js") %>"></script>

<%= if get_flash(@conn, :info) do %>
<script>
        $(document).ready(function() {

            setTimeout(function() {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 4000
                };
                toastr.info("<%= get_flash(@conn, :info) %>");

            }, 1300);
            });
    </script>
<% end %>


<%= if get_flash(@conn, :error) do %>
<script>
        $(document).ready(function() {

            setTimeout(function() {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 4000
                };
                toastr.error("<%= get_flash(@conn, :error) %>");

            }, 1300);
            });
    </script>
<% end %>


  </body>
</html>

lib/brickcroft_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Brickcroft Construction Ltd Company Website">
    <meta name="author" content="Le Proghrammeen Solutions Ltd">

    <title>BrickCroft Construction</title>

    <!-- Browser Tab Icon -->
	<link rel="icon" href="/img/favicon.jpg">

    <!-- Bootstrap core CSS -->
    <link href="<%= Routes.static_path(@conn,"/web/bootstrap/css/bootstrap.css") %>" rel="stylesheet" type="text/css">

    <!-- Font Link -->
	<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">



    <!-- Custom Stylesheet -->
	<link href="<%= Routes.static_path(@conn,"/css/web/style.css") %>" rel="stylesheet" type="text/css">
	<link href="<%= Routes.static_path(@conn,"/css/web/style.responsive.css") %>" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="<%= Routes.static_path(@conn,"/web/slick/slick.css") %>" />

    <!-- Other Stylesheets -->
	<link rel="stylesheet" href="<%= Routes.static_path(@conn,"/web/font-awesome/css/font-awesome.css") %>">


</head>

<body>
<header class="masthead masthead <%= cond     do %> <%= @conn.request_path == "/" ->  %> home-page-masthead  <%= @conn.request_path == "/about" ->  %> banner-page-masthead  <%= @conn.request_path == "/contact" ->  %> banner-page-masthead  <%= true -> %> other-page-masthead <% end %>">
		<div class="topNav py-4">
			<div class="d-flex">
				<div class="mx-2">
					<img src="<%= Routes.static_path(@conn,"/img/Truck-01.png") %>" alt="">
					<span>

					<%= if @settings.header_address do %>
                      			  <%= @settings.header_address %>
                      			<% end %>
					</span>
				</div>
				<div class="mx-2">
					<img src="/img/phone-01.png" alt="">
					<span>

					<%= if @settings.header_phones do %>
                                          			  <%= @settings.header_phones %>
                                          			<% end %></span>
				</div>
				<div class="mx-2">
					<img src="/img/Message-01.png" alt="">
					<span>
					<%= if @settings.header_email do %>
                                          			  <%= @settings.header_email %>
                                          			<% end %>
					</span>
				</div>
			</div>
			<div class="ml-auto top-nav-icons">
				 s
				<span><a href=""><img src="/img/instagram-logo-white.png" alt=""></a></span>
				<span><a href=""><img src="/img/twitter-logo-button-white.png" alt=""></a></span>
			</div>
		</div>
<%= render BrickcroftWeb.LayoutView, "nav.html" , conn: @conn %>

        <%= if @conn.request_path == "/" do  %>
		<div class="header-text mt-5">
			<h1 class="text-white text-center font-weight-bold">Construction Company</h1>
		</div>

		<% end %>

        <%= if @conn.request_path == "/about" do  %>
		<div class="header-text mt-5 pt-5 d-flex justify-content-center align-items-center flex-column">
                    <h1 class="text-white text-center font-weight-bold">About us</h1>
                    <h4 class="text-white text-center w-75">
                   BrickCroft is a contemporary construction company inclined towards world class constructions, general contracts and import and export of general merchandise.

                        </h4>
        		</div>
        		<% end %>
 <%= if @conn.request_path == "/contact" do  %>
<div class="header-text mt-5 pt-5 d-flex justify-content-center align-items-center flex-column">
            <h1 class="text-white text-center font-weight-bold">Contact Us</h1>
            <h4 class="text-white text-center w-75">
            BrickCroft is a contemporary construction company inclined towards world class constructions, general contracts and import and export of general merchandise.
            </h4>
		</div>
		<% end %>
<%= if @conn.request_path == "/team" do  %>
		<div class="header-text mt-5 pt-5 d-flex justify-content-center align-items-center flex-column">
                    <h1 class="text-white text-center font-weight-bold">Our Team</h1>
                </div>
                <% end %>

	</header>

  <%= render @view_module, @view_template, assigns %>


  <footer>

  		<div class="row mx-0 footer">
  			<div class="col-md-6">
  				<a class="font-weight-bold footer-logo text-uppercase" href="#"><span>Brick</span>croft</a>
  				<p class="">
  			<%= if @settings.footer_brief_pitch do %>
  			  <%= @settings.footer_brief_pitch %>
  			<% end %>
  						</p>
  			</div>
  			<div class="col-md-6">
  				<h2>What we do</h2>
  				<p class="">
  				<%= if @settings.footer_brief_pitch do %>
                  			  <%= @settings.footer_brief_service %>
                  			<% end %>
  						</p>
  			</div>
  		</div>
  		<div class="copyright text-center py-3">
  			<span>All Rights Reserved <%= DateTime.utc_now.year %></span>
  		</div>

  	</footer>


    <script src="<%= Routes.static_path(@conn,"/js/web/js/jquery.js") %>"></script>
    <script src="<%= Routes.static_path(@conn,"/web/bootstrap/js/bootstrap.js") %>"></script>
		<script type="text/javascript" src="<%= Routes.static_path(@conn,"/web/slick/slick.min.js") %>"></script>


	<script src="<%= Routes.static_path(@conn,"/js/web/js/scripts.js") %>"></script>




</body>

</html>

lib/brickcroft_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>

    <%= render @view_module, @view_template, assigns %>
    <p>- The BCL Team.</p>
  </body>
</html>

lib/brickcroft_web/templates/layout/email.text.eex
<%= render @view_module, @view_template, assigns %>

- The BCL Team.

lib/brickcroft_web/templates/layout/nav.html.eex
		<nav class="navbar navbar-expand-lg navbar-light custom-navbar">
			<a class="navbar-brand font-weight-bold custom-logo text-uppercase" href="<%= Routes.page_path(@conn,:index) %>"><span>Brick</span>Croft</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link custom-nav-link" href="<%= Routes.page_path(@conn,:index) %>">HOME</a>
					</li>
					<li class="nav-item">
						<a class="nav-link custom-nav-link" href="<%= Routes.page_path(@conn,:show_by_slug,"portfolio") %>">PORTFOLIO</a>
					</li>
					<li class="nav-item">
						<a class="nav-link custom-nav-link" href="<%= Routes.page_path(@conn,:show_by_slug, "about") %>">ABOUT US</a>
					</li>
					<li class="nav-item">
                    						<a class="nav-link custom-nav-link" href="<%= Routes.page_path(@conn,:show_by_slug,"team") %>">OUR TEAM</a>
                    					</li>
					<li class="nav-item">
						<a class="nav-link custom-nav-link" href="<%= Routes.page_path(@conn,:show_by_slug, "contact") %>">CONTACT US</a>
					</li>
				</ul>
			</div>
		</nav>